spring.application.name=demo

# Configuración de la Base de Datos MySQL
# Cambia 'localhost:3306/veterinaria_db' por tu host y nombre de BD
spring.datasource.url=jdbc:mysql://localhost:3306/Veterinaria_bd?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
